# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install MCP and dependencies
RUN pip install --no-cache-dir httpx mcp

# Copy server script
WORKDIR /app
COPY weather.py .

# Run the MCP server
CMD ["python", "weather.py"]
